const fs = require('fs');
const path = require('path');

const tsCode = `export type GalleryItem = {
  src: string;
  label: string;
  cat: string[];
  ask: boolean;
};

export const GALLERY_ITEMS: GalleryItem[] = [
  { "src": "/gallery/img1.jpeg", "label": "Kiswa Mill Production Floor Overview", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img2.jpeg", "label": "Power Loom Weaving Area — View 2", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img3.jpeg", "label": "Yarn Preparation — Detail 3", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img4.jpeg", "label": "Power Loom Weaving Area — View 4", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img5.jpeg", "label": "Yarn Preparation — Detail 5", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img6.jpeg", "label": "Yarn Preparation — Detail 6", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img7.jpeg", "label": "Yarn Spinning & Threading Area — Setup 7", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img8.jpeg", "label": "Yarn Spinning & Threading Area — Setup 8", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img9.jpeg", "label": "Yarn Spinning & Threading Area — Setup 9", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img10.jpeg", "label": "Fabric Checking Station — Detail 10", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img11.jpeg", "label": "Finished Fabric Warehousing & Packing — Detail 11", "cat": ["all", "packing"], "ask": false },
  { "src": "/gallery/img12.jpeg", "label": "Yarn Spinning & Threading Area — Setup 12", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img13.jpeg", "label": "Power Loom Weaving Process — Detail 13", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img14.jpeg", "label": "Yarn Preparation — Detail 14", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img15.jpeg", "label": "Yarn Preparation — Detail 15", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img16.jpeg", "label": "Yarn Preparation — Detail 16", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img17.jpeg", "label": "Yarn Preparation — Detail 17", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img18.jpeg", "label": "Yarn Preparation — Detail 18", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img19.jpeg", "label": "Finished Fabric Warehousing & Packing — Detail 19", "cat": ["all", "packing"], "ask": false },
  { "src": "/gallery/img20.jpeg", "label": "Finished Fabric Warehousing & Packing — Detail 20", "cat": ["all", "packing"], "ask": false },
  { "src": "/gallery/img21.jpeg", "label": "Power Loom Weaving Process — Detail 21", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img22.jpeg", "label": "Power Loom Weaving Process — Detail 22", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img23.jpeg", "label": "Power Loom Weaving Process — Detail 23", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img24.jpeg", "label": "Power Loom Weaving Process — Detail 24", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img25.jpeg", "label": "Power Loom Weaving Process — Detail 25", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img26.jpeg", "label": "Power Loom Weaving Process — Detail 26", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img27.jpeg", "label": "Power Loom Weaving Area — View 27", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img28.jpeg", "label": "Power Loom Weaving Process — Detail 28", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img29.jpeg", "label": "Power Loom Weaving Area — View 29", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img30.jpeg", "label": "Power Loom Weaving Machinery Row", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img31.jpeg", "label": "Power Loom Weaving Area — View 31", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img32.jpeg", "label": "Power Loom Weaving Area — View 32", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img33.jpeg", "label": "Fabric Calendering & Finish — Detail 33", "cat": ["all", "printing"], "ask": true },
  { "src": "/gallery/img34.jpeg", "label": "Weaving & Loom Section — View 34", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img35.jpeg", "label": "Weaving & Loom Section — View 35", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img36.jpeg", "label": "Weaving & Loom Section — View 36", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img37.jpeg", "label": "Fabric Calendering & Finish — Detail 37", "cat": ["all", "printing"], "ask": true },
  { "src": "/gallery/img38.jpeg", "label": "Weaving & Loom Section — View 38", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img39.jpeg", "label": "Fabric Calendering & Finish — Detail 39", "cat": ["all", "printing"], "ask": true },
  { "src": "/gallery/img40.jpeg", "label": "Fabric Calendering & Finish — Detail 40", "cat": ["all", "printing"], "ask": true },
  { "src": "/gallery/img41.jpeg", "label": "Fabric Calendering & Finish — Detail 41", "cat": ["all", "printing"], "ask": true },
  { "src": "/gallery/img42.jpeg", "label": "Fabric Washing Section — Detail 42", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img43.jpeg", "label": "Fabric Calendering & Finish — Detail 43", "cat": ["all", "printing"], "ask": true },
  { "src": "/gallery/img44.jpeg", "label": "Fabric Washing Section — Detail 44", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img45.jpeg", "label": "Fabric Washing Section — Detail 45", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img46.jpeg", "label": "Weaving & Loom Section — View 46", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img47.jpeg", "label": "Fabric Washing Section — Detail 47", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img48.jpeg", "label": "Fabric Washing Section — Detail 48", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img49.jpeg", "label": "Fabric Washing Section — Detail 49", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img50.jpeg", "label": "Fabric Washing Section — Detail 50", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img51.jpeg", "label": "Fabric Washing Section — Detail 51", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img52.jpeg", "label": "Fabric Preprocessing Washing — Detail 52", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img53.jpeg", "label": "Fabric Preprocessing Washing — Detail 53", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img54.jpeg", "label": "Fabric Preprocessing Washing — Detail 54", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img55.jpeg", "label": "Fabric Washing Section — Detail 55", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img56.jpeg", "label": "Fabric Preprocessing Washing — Detail 56", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img57.jpeg", "label": "Fabric Preprocessing Washing — Detail 57", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img58.jpeg", "label": "Fabric Preprocessing Washing — Detail 58", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img59.jpeg", "label": "Fabric Preprocessing Washing — Detail 59", "cat": ["all", "dyeing"], "ask": true },
  { "src": "/gallery/img60.jpeg", "label": "Warehouse Finished Rolls — Stock 60", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img61.jpeg", "label": "Warehouse Finished Rolls — Stock 61", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img62.jpeg", "label": "Weaving Setup & Loom Warp — Detail 62", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img63.jpeg", "label": "Warehouse Finished Rolls — Stock 63", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img64.jpeg", "label": "Warehouse Finished Rolls — Stock 64", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img65.jpeg", "label": "Weaving Setup & Loom Warp — Detail 65", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img66.jpeg", "label": "Warehouse Finished Rolls — Stock 66", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img67.jpeg", "label": "Warehouse Finished Rolls — Stock 67", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img68.jpeg", "label": "Weaving Setup & Loom Warp — Detail 68", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img69.jpeg", "label": "Weaving Setup & Loom Warp — Detail 69", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img70.jpeg", "label": "Warehouse Finished Rolls — Stock 70", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img71.jpeg", "label": "Weaving Setup & Loom Warp — Detail 71", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img72.jpeg", "label": "Warehouse Finished Rolls — Stock 72", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img73.jpeg", "label": "Warehouse Finished Rolls — Stock 73", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img74.jpeg", "label": "Weaving Setup & Loom Warp — Detail 74", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img75.jpeg", "label": "Warehouse Finished Rolls — Stock 75", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img76.jpeg", "label": "Power Loom Weaving Area — View 76", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img77.jpeg", "label": "Power Loom Weaving Area — View 77", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img78.jpeg", "label": "Warehouse Finished Rolls — Stock 78", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img79.jpeg", "label": "Warehouse Finished Rolls — Stock 79", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img80.jpeg", "label": "Weaving Setup & Loom Warp — Detail 80", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img81.jpeg", "label": "Weaving Setup & Loom Warp — Detail 81", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img82.jpeg", "label": "Warehouse Finished Rolls — Stock 82", "cat": ["all", "rolls"], "ask": false },
  { "src": "/gallery/img83.jpeg", "label": "Power Loom Weaving Area — View 83", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img84.jpeg", "label": "Power Loom Weaving Area — View 84", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img85.jpeg", "label": "Weaving Setup & Loom Warp — Detail 85", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img86.jpeg", "label": "Weaving Setup & Loom Warp — Detail 86", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img87.jpeg", "label": "Weaving Setup & Loom Warp — Detail 87", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img88.jpeg", "label": "Yarn Preparation — Detail 88", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img89.jpeg", "label": "Shipping Dispatch Loader — View 89", "cat": ["all", "packing"], "ask": false },
  { "src": "/gallery/img90.jpeg", "label": "Yarn Preparation — Detail 90", "cat": ["all", "factory"], "ask": false },
  { "src": "/gallery/img91.jpeg", "label": "Shipping Bales Dispatch — View 91", "cat": ["all", "packing"], "ask": false }
];
`;

fs.writeFileSync(path.resolve(__dirname, '../lib/gallery-items.ts'), tsCode);
console.log("Successfully wrote categorized, single-category mapped items to lib/gallery-items.ts!");
